### ISSUE TITLE
Instructor Overview

### ISSUE THREAD

**Issue by lwgray** [georgetown-analytics/webfolio#10]
The first thing I wanted to know when I visited the site was "when do I teach next?". Thus  I think we should immediately see a breakdown of only our individual course loads.

**Comment by bbengfort** [comment]
@lwgray ok I created something lightweight for this - you can click on your profile link under your name and you should see your current and upcoming courses. This is still pretty lightweight so any suggestions/coding you want to do on this - let me know! Also happy to draft up a wireframe for it.

**Comment by lwgray** [comment]
this works!
